### PR TITLE
override any manualChunks from the user config

### LINKED ISSUE #57: RollupError: Invalid value for option "output.manualChunks" - this option is not supported for "output.inlineDynamicImports".
I use `build.rollupOptions.output.manualChunks`:
```ts
// cypress.config.ts
export default defineConfig(() => {
    return {
        build: {
            rollupOptions: {
                output: {
                    manualChunks: {
                        globals: ["src/globals.ts"],
                        Ship: ["src/Ship.ts"],
                        Component: ["src/Component.ts"],
                        mathjs: ["mathjs"],
                    },
                },
            },
        },
        plugins: [vue()],
        // ... etc ...
    };
});
```

This causes cypress-vite to just... not work
image

### PR DESCRIPTION
**Pull request by SIGSTACKFAULT**
low effort solution, but works. fixes #57.

### CODE REVIEW

**Review by mammadataei — APPROVED** [review]

**Comment by mammadataei** [comment]
@SIGSTACKFAULT Thanks for your contribution.

Typescript is not happy with the `false` value. Can you please check whether using `undefined` fixes the issue?

**Review by mammadataei — APPROVED** [review]

**Comment by SIGSTACKFAULT** [comment]
...and it doesn't actually work when it's `undefined`. only `false` seems to work.

**Comment by SIGSTACKFAULT** [comment]
`{}` and `() => void` don't work either because they technically exist despite not doing anything

**Comment by mammadataei** [comment]
Oh, I thought it worked with `undefined`. If it only works with `false`, then it might be a typing issue. I will open a new issue and create a new pull request to fix it.

**Pull request merged**
